apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfga
  template:
    metadata:
      labels:
        app: openfga
    spec:
      containers:
        - name: openfga
          image: openfga/openfga:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
          command: ["openfga", "run"]
          env:
            - name: OPENFGA_DATASTORE_ENGINE
              value: postgres
            - name: OPENFGA_DATASTORE_URI
              value: postgres://openfga:$(DB_PASSWORD)@openfga-db-svc:5432/openfga?sslmode=disable
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openfga-db-secret
                  key: password
            - name: OPENFGA_LOG_FORMAT
              value: json
