apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openfga-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# Deployment for OpenFGA Postgres Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga-db-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openfga-db
  template:
    metadata:
      labels:
        app: openfga-db
    spec:
      containers:
        - name: openfga-db
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "openfga"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openfga-db-secret
                  key: password
            - name: POSTGRES_DB
              value: "openfga"
            - name: PGDATA
              value: /var/lib/postgresql/18/docker/data
          volumeMounts:
            - mountPath: /var/lib/postgresql/18/docker
              name: openfga-db-storage
      volumes:
        - name: openfga-db-storage
          persistentVolumeClaim:
            claimName: openfga-db-pvc
---
# Service for OpenFGA Postgres Database
apiVersion: v1
kind: Service
metadata:
  name: openfga-db-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: openfga-db
