replicaCount: 1

image:
  repository: openfga/openfga
  tag: "v1.6.2"

datastore:
  engine: postgres
  postgres:
    host: openfga-db-svc
    port: 5432
    user: openfga_user
    password: openfga_pass
    database: openfga
    sslMode: disable

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
